### ISSUE TITLE
[openGithubProject.sh] Compatibility with non OS X systems

### ISSUE THREAD

**Issue by n-eq** [ShaydeNofziger/development_scripts#2]
Non OS X users might be concerned with this issue.
In fact, the `open` command used to open the link in a browser does not exist in Linux distros.
In order to solve this problem, you can change the line in question to one of the following (depending on the program installed in your system):
* `xdg-open "${url}"`
* `gnome-open "${url}"`

Unfortunately I don't know of any program that is compatible with both OS X and Linux systems.
Again not a huge deal, just wanted to point this out in case anyone didn't know how to solve it.

**Comment by pschfr** [comment]
`sensible-browser` works as well, see [this AskUbuntu post](https://askubuntu.com/questions/8252/how-to-launch-default-web-browser-from-the-terminal)

**Comment by n-eq** [comment]
@pschfr Absolutely, the only concern I had is that `sensible-browser` may not exist (be packaged) on every Linux distro.

**Comment by n-eq** [comment]
Actually I'm very likely wrong, as `xdg-open` seems to be using `sensible-browser`. However, it's more a general command and therefore properly covers more use cases than `sensible-browser`. You might want to take a look [at this discussion](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=539191).

**Comment by pschfr** [comment]
Wow! It definitely looks like we should use `xdg-open`!

**Comment by pschfr** [comment]
This probably could be closed?

**Comment by n-eq** [comment]
It's up to the repo's owner, he doesn't seem to address this issue anyway.
